### ISSUE TITLE
Add ScreenShot as a Standard Action

### ISSUE THREAD

**Issue by accessor-io** [Jmgr/actiona#213] opened 2023-12-31 16:18 UTC
I request that screenshots are added as a preloaded action.
On Ubuntu and the keyboard I have, does not register the PrtSc key when requested to capture a key, using the 'key' action.
Can't find another solution to automate Screen Shots.

**Comment by gitvectors** [comment] 2024-04-15 20:43
Flameshot in Ubuntu is one option by command line.

**Comment by Jmgr** [comment] 2024-05-06 21:41
That's a good idea, and should not be very complicated to implement, too. Thanks.

**Comment by Jmgr** [comment] 2024-05-06 21:43
Actually this is a duplicate of https://github.com/Jmgr/actiona/issues/205

**Closed by Jmgr** 2024-05-06 21:43 UTC
Labels: enhancement, actions

**Comment by accessor-io** [comment] 2024-05-07 06:52
are you on telegram?
