### ISSUE TITLE
QXcbClipboard::setMimeData: Cannot set X11 selection owner

### ISSUE THREAD

**Issue by fro0m** [Jmgr/actiona#85] opened 2018-09-14 20:04 UTC
`QXcbClipboard::setMimeData: Cannot set X11 selection owner`
copy and paste does not work and the message above is shown

I start actexec with ascr file and get such log
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Invalid type of WM_NAME property.

Invalid type of WM_NAME property.


QXcbClipboard::setMimeData: Cannot set X11 selection owner
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1281, resource id: 35653357, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1282, resource id: 35653357, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1284, resource id: 35653360, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1285, resource id: 35653360, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1287, resource id: 35653363, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1288, resource id: 35653363, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1290, resource id: 35653366, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1291, resource id: 35653366, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1293, resource id: 35653369, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1294, resource id: 35653369, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1296, resource id: 35653372, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1297, resource id: 35653372, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1299, resource id: 35653375, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1300, resource id: 35653375, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1303, resource id: 35653378, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1306, resource id: 35653381, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1309, resource id: 35653384, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1312, resource id: 35653387, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1315, resource id: 35653390, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1318, resource id: 35653393, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1321, resource id: 35653396, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1324, resource id: 35653399, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1327, resource id: 35653402, major code: 25 (SendEvent), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1329, resource id: 35653405, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1330, resource id: 35653405, major code: 25 (SendEvent), minor code: 0

```
--------------
envirement:
Lubuntu 18.04 x64 LXDE

**Comment by Jmgr** [comment] 2018-09-14 21:13
Are you using the version of Actiona in the repositories? This is strange, I will try to reproduce this here.

**Comment by fro0m** [comment] 2018-09-15 06:01
yes. from repository.

the ascr file actively use block `Code` with use of such functions
```
function copyPaste(text) {
	var myObject = new Clipboard();
	myObject.setText(text);

	keypress("v", "controlLeft");

	Execution.pause(getRandomInt(2000))
}
```
```
function activateTor() {
	var torTitle = "*Tor Browser";
	var windows = Window.find({
		title: torTitle,
		titleMode: Window.Wildcard
	});
	while (windows.length === 0)
	{
		Execution.pause(1000);
		windows = Window.find({
			title: torTitle,
			titleMode: Window.Wildcard
		});
	}
	windows[0].setForeground();
	keypress("return") // to activate window
}
```

**Comment by Jmgr** [comment] 2018-09-15 08:12
I am not able to reproduce this issue on a Ubuntu 18.04 virtual machine with LXDE installed.
Could you run `echo $XDG_SESSION_TYPE` in a terminal? It should output x11.

**Comment by Jmgr** [comment] 2018-10-03 21:09
I've sent you an e-mail. Could you send me your script please, so I can try to reproduce the issue?

**Comment by fro0m** [comment] 2018-10-12 07:50
i just did not get an email from you. I just list code below
this code is adjusted for windows, as on linux I faced with issues, i reported.

```
function log(string) {
	Console.print(string);
}

function osName() {
	return new System().osName();
}

function message(text) {
	var myObject = new MessageBox({"text": text});
	myObject.setEnabled(true);
	myObject.setVisible(true);
	myObject.showModal();
}

function getRandomInt(max) {
  return Math.floor(Math.random() * Math.floor(max));
}

function processLogins() {
	var logins = [];
	var filename = "logins.txt";

	var file = new File();
	file = file.open(rootDir + filename, File.ReadOnly | File.Text);
	
	logins = file.readText();
	logins = logins.split(/\s+/)

	return logins;
}

function getCurrentUserId() {
	keypress("l", "controlLeft") // highlight address

	Execution.pause(5000)

	keypress("c", "controlLeft")

	var clipboard = new Clipboard();
	var userId = clipboard.text;
	userId = userId.match(/\d/g);
	userId = userId.join('');

	return userId;
}

// activates tor window
function activateTor() {
	var torTitle = "*Tor Browser";
	var windows = Window.find({
		title: torTitle,
		titleMode: Window.Wildcard
	});
	while (windows.length === 0)
	{
		Execution.pause(1000);
		windows = Window.find({
			title: torTitle,
			titleMode: Window.Wildcard
		});
	}
	windows[0].setForeground();
	keypress("return") // to activate window
}

function minimizeTor() {
	var torTitle = "*Tor Browser";
	var windows = Window.find({
		title: torTitle,
		titleMode: Window.Wildcard
	});
	if (windows.length === 0) {
		return
	}
	windows[0].minimize()
}

function click(position) {
	var myObject = new Mouse();
	myObject.move(position);
	myObject.click();

	Execution.pause(500)
}

function keypress(key, modifier) {
	var keyboard = new Keyboard();
	if(modifier) {
		keyboard.pressKey(modifier);
	}
	keyboard.triggerKey(key);
	if(modifier) {
		keyboard.releaseKey(modifier);
	}

	Execution.pause(500)
}

function writeText(text) {
	var keyboard = new Keyboard();
	keyboard.writeText(text, Math.floor(Math.random() * 100));
}

function copyPaste(text) {
	var myObject = new Clipboard();
	myObject.setText(text);

	keypress("v", "controlLeft");
	Execution.pause(getRandomInt(2000))
}

function goToSite(address, delay) {
	keypress("l", "controlLeft");
	writeText(address)
	keypress("return")

	if(!delay) {
		delay = 15000
	}

	Execution.pause(delay);
}

function getImagePosition(filename) {
	var screenshot = Image.takeScreenshot();
	var file = new Image(filename);
	return screenshot.findSubImage(file);
}

function findImage(filename) {
	var searchResult = getImagePosition(filename);
	if(searchResult)
	{
	 	return searchResult.position
	}
	else 
	{
		message("stopped " + filename + " is not found")
	    Execution.stop();
	}
}

function enterVkSite(login, password) {
	goToSite("vk.com")

	writeText(login)
	keypress("tab")
	writeText(password)
	keypress("return")

	Execution.pause(15000);
}

function setSettings() {
	goToSite("vk.com\\settings", 10000)
	var position = findImage(rootDir + imgPath + "showOnlyMyPosts.jpg")
	click(position)	

	position = findImage(rootDir + imgPath + "disableWallComments.png")
	click(position)	
}

function goMyProfile() {
	var position = findImage(rootDir + imgPath + "myProfile.png")
	click(position)
	Execution.pause(10000)
}

function setStatus() {
	position = findImage(rootDir + imgPath + "setStatus.png")
	click(position)

	Execution.pause(1000)

	var statuses = [
		"Наслаждайся и Развивайся",
		"Время не приходит, оно уходит",
		"Я деньги не люблю! Просто я люблю то, что на них можно купить!",
		"Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
		"Стремитесь не к успеху, а к ценностям, которые он дает​",
		"Своим успехом я обязана тому, что никогда не оправдывался и не принимала оправданий от других.",
		"Сложнее всего начать действовать, все остальное зависит только от упорства.",
		"Надо любить жизнь больше, чем смысл жизни.",
		"Жизнь - это то, что с тобой происходит, пока ты строишь планы.",
		"Логика может привести Вас от пункта А к пункту Б, а воображение — куда угодно.",
		"Начинать всегда стоит с того, что сеет сомнения.",
		"Настоящая ответственность бывает только личной.",
		"Неосмысленная жизнь не стоит того, чтобы жить.",
		"80% успеха - это появиться в нужном месте в нужное время.",
		"Ваше время ограничено, не тратьте его, живя чужой жизнью",
		"Победа - это еще не все, все - это постоянное желание побеждать.",
		"В моем словаре нет слова «невозможно».",
		"Вы никогда не пересечете океан, если не наберетесь мужества потерять берег из виду.",
		"Свобода ничего не стоит, если она не включает в себя свободу ошибаться.",
		"Либо вы управляете вашим днем, либо день управляет вами.",
		"Если вы думаете, что на что-то способны, вы правы; если думаете, что у вас ничего не получится - вы тоже правы.",
		"Два самых важных дня в твоей жизни: день, когда ты появился на свет, и день, когда понял, зачем."
	]

	copyPaste(statuses[getRandomInt(statuses.length - 1)])
	Execution.pause(1000)
	keypress("return")

	Execution.pause(3000)
}

function loadPhotos(userId) {
	// initialize path
	var path = "";
	if(osName() !== "Windows")
	{
		path += "/";
	}
	path += rootDir + "photos/" + (Math.floor(Math.random() * Math.floor(22)) + 1)

	// open tabs
	for(var i = 0; i < 4; ++i) {
		keypress("t", "controlLeft")
		Execution.pause(1000)
		keypress("l", "controlLeft")
		writeText("vk.com\\id"+ userId)
		Execution.pause(1000)
		keypress("return")
		Execution.pause(1000)
	}

	function loadPhoto(index, path) {
		var position = findImage(rootDir + imgPath + "defaultAvatar.png")
		click(position)
		Execution.pause(7000 + getRandomInt(1000))

		position = findImage(rootDir + imgPath + "selectFileButton.png")
		click(position)
		Execution.pause(7000 + getRandomInt(1000))

		if(osName() !== "Windows")
		{
			keypress("l", "controlLeft")
			Execution.pause(1000)
		}
		path = (path + "/" + index + ".jpg")
		if(osName() !== "Windows")
		{
			path = path.replace(/\//g, '\u002F');
		}
		else
		{
			path = path.replace(/\//g, '\\');
		}
		writeText((path)) // substitute with '/'
		Execution.pause(500)
		log("photo path is entered")
		keypress("return")

		Execution.pause(12000 + getRandomInt(1000))

		keypress("tab")
		keypress("return")
		Execution.pause(1000 + getRandomInt(1000))

		keypress("tab")
		keypress("return")

		Execution.pause(10000 + getRandomInt(1000))
	}

	Execution.pause(10000)

	for(var i = 1; i < 5; ++i) {
		loadPhoto(i, path)
		keypress("w", "controlLeft")

		Execution.pause(2000)
	}


}
function  fillBasicInfo() {
	goToSite("https://vk.com/edit?act=contacts")

	var position = findImage(rootDir + imgPath + "mobile.jpg")
	click(position)

	writeText("*****" + Math.floor(Math.random() * 988889))

	position = findImage(rootDir + imgPath + "save.png")
	click(position)
	Execution.pause(1000)

	goToSite("https://vk.com/edit?act=interests")
	position = findImage(rootDir + imgPath + "activities.png")
	click(position)

	// активности
	var activities = 
	[
		"Учусь в хогвартсе",
		"Начальник участка",
		"Развожу рыбок в аквариуме",
		"Ищу клад",
		"Бью деревья кулаком",
		"Шил, шью и буду шить",
		"Развожу пчел на мед, а остальных — на деньги.",
		"Подгрызаю моральные устои, посасываю гранит науки, подливаю масло в огонь, антогонирую сам себе",
		"Без труда свожу людей с ума, молча совсем, просто глядя в глаза.",
		"Правлю миром",
		"Разрабатываю план по захвату Вселенной",
		"Заместитель главаря банды веселых дворников",
		"Главный по главным",
		"В поисках смысла жизни…",
		"Выношу мозг",
		"Играю на нервах!",
		"Дарю людям улыбки.",
		"Ищу приключения на свою пятую точку!",
		"Общество защиты мальтийских тушканчиков.",
		"Фигнестралец…",
		"Член общества людей, которые однажды дотронулись языком до замерзшей железки.",
		"Мочу огурцы в рассоле",
		"Активная мозговая деятельность.",
		"Если скажу - меня выследит ЦРУ.",
		"Я работаю в голове мозгоедом.",
		"Стреляю по лягушкам лазером из космоса со спутника.",
		"Гоняю по жизни в поисках смысла.",
		"Бетман",
		"Человек бабочка",
		"Спайдермен",
		"Супермен",
		"Человек тушканчин",
		"Наблюдаю солнце без очков",
		"Справляюсь с пищеварением"
	];
	writeText(activities[getRandomInt(activities.length - 1)])

	keypress("tab")

	// интересы
	var interests = 
	[
		"ухажимвать за собой",
		"чертить черчежи",
		"гулять",
		"мыться",
		"играть на барабанах",
		"убиваться",
		"достопримечательности",
		"экскурсии",
		"квесты",
		"музеи",
		"туризм",
		"друзья",
		"кушать вкусную еду",
		"ездить на лошадях",
		"коты",
		"собаки",
		"динозавны",
		"машины",
		"стиль",
		"гаджеты",
		"психология",
		"спорт",
		"здоровое питание"
	];

	var interestesToWrite = "";
	for (var i = 0; i < interests.length; ++i)
	{
		interestesToWrite += Math.random() > 0.2 ? "": interests[i] + ", ";
	}
	copyPaste(interestesToWrite)

	for (var i = 0; i < 8; ++i)
	{
		keypress("tab")
		Execution.pause(getRandomInt(500))
	}
	keypress("return")
	Execution.pause(200 + getRandomInt(800))
}

function joinGroups() {
	function findJoinButton() {
		var butonsImages = ["joinCommunity.png", "follow.png", "subscribe.png", "addToFriends.png"];
		var position = undefined;
		for(var i = 0; i < butonsImages.lengt; ++i)
		{
			position = getImagePosition(rootDir + imgPath + butonsImages[i]);
			if (position)
				retrun position;
		}
		message("stopped " + filename + " is not found")
	    Execution.stop();
	}

	var vkSite = "vk.com/"

	var requiredGroups = 
	[
		"ubego"
	]

	var groups =
	[
		"polity20",
		"cashbackcards",
		"be_organized_supreme",
		"club106082773",
		"prilozhenievpodarok",
		"gonature",
		"bos_gtd20",
		"myplace_lap",
		"gearbestbest",
		"kudago",
		"afisha",
		"kudagospb",
		"afishapicnic",
		"afishakyiv",
		"kzngo",
		"piter_events",
		"afishamsk1",
		"afisha_nnov",
		"zavtra_v_moskve",
		"piterbesplatno",
		"piteronline24",
		"ekb_afisha	",
		"kudakrsk",
		"64afisha",
		"flet_minsk",
		"permafisha",
		"afisha_vinnitsa",
		"piter_event",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		""
	]
}

function addVkApp() {
	// todo fill
}

function newIdentity() {
	// todo fill
}


// start
var rootDir = "C:/dev/prj/socialnetworksregger-master/"
var imgPath = "images/win/"
var logins = processLogins();
// message("\u002F") is '/' character
log("rootDir is " + rootDir);

Execution.pause(3000)

for(var i = 0; i < logins.length; ++i) {
	var currentLogin = logins[i];

	activateTor();
	 Execution.pause(1000);
	
	enterVkSite(currentLogin, "password") 

	setSettings()

	goMyProfile()

	setStatus()

	goMyProfile()
	Execution.pause(7000)

	var userId = getCurrentUserId()
	loadPhotos(userId)

	fillBasicInfo()

	joinGroups()

	addVkApp() 

	newIdentity()
}

```

**Comment by Jmgr** [comment] 2020-03-17 22:57
Closing because of age and inability to reproduce the problem, but don't hesitate to comment if this is still an issue.

**Closed by Jmgr** 2020-03-17 22:57 UTC

**Comment by tsvigo** [comment] 2024-02-01 06:36
The problem will never die. Twitching the "killall plasma shell" cures, but there should be an easier way.
