### ISSUE TITLE
not available for debian bullseye?

### ISSUE THREAD

**Issue by caresse** [Jmgr/actiona#196] opened 2023-08-16 13:11 UTC
hi 
i m on pi os, 
source list is deb http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi
no actiona available.
can you make it available or how to install it?
thank you.

**Comment by caresse** [comment] 2023-08-17 10:38
i see there is no answer for all precedent issue posted. has this project been abandoned? if so, is there an updated fork or close alternative? thank you

**Comment by Jmgr** [comment] 2023-08-18 22:45
Hi, yes development and support has been a bit slow, as I have to admit that after 18 years of being the only developer on this project I moved on a little bit.

Anyway, I haven't tried running Actiona on a Raspberry Pi. Its biggest dependencies are the Qt framework and X11, and I guess those should be available there. I see it is still in the [repos](https://packages.debian.org/bullseye/actiona). I'm not the maintainer for the Debian packages though.

@adri2000 are you still maintaining it? Any idea why it could be invisible on that platform?

**Comment by caresse** [comment] 2023-08-21 16:46
thank you for your valuable project @Jmgr 

it's worked and still work fine on precedent version of Debian (10 buster or 9 stretch) on raspberry. i have 3 raspberry, actionna on old version work fine. but not with the most recent version : 

Debian Bullseye with Raspberry Pi Desktop
Release date: July 1st 2022
System: 32-bit
Kernel version: 5.10
Debian version: 11 (bullseye)

deb http://raspbian.raspberrypi.org/raspbian/ bullseye main contrib non-free rpi

**Comment by Jmgr** [comment] 2023-08-22 08:51
Thanks for the details. I'll have a look to see if I can reproduce the issue locally.

**Comment by Jmgr** [comment] 2023-08-28 10:03
I was not able to get Raspberry Pi Desktop to work on a VirtualBox instance unfortunately. The installation fails for some reason. Anyway, I'll try to get my hand on a new Raspberry Pi and try there (the ones I have are all currently in use :slightly_smiling_face: ).

**Comment by Jmgr** [comment] 2023-08-31 11:17
I bought a RPI 4 and installed a fresh Raspberry Pi Desktop on it (based on Debian Bulleye) and was able to install and run Actiona using `sudo apt install actiona`, so I'm not sure why you are seeing this issue. It could be that your apt package list is outdated?

**Comment by Jmgr** [comment] 2023-09-30 21:34
Closing for now, but let me know if the issue is still present.

**Closed by Jmgr** 2023-09-30 21:34 UTC
