### ISSUE TITLE
Loading window is always shown

### ISSUE THREAD

**Issue by sojusnik** [Jmgr/actiona#97] opened 2019-03-24 07:05 UTC
Although the appropriate option in the settings is turned off, the loading window is always shown at startup, as depicted [here](https://mega.nz/#!v5AAxQzC!jCcFjY4d-T6jVFcj1Ct3-oa0FO3t4UDb0zWP_3lP6lE).

Happens with Actiona 3.9.4-1 from the Ubuntu 18.10 repository.

**Comment by Jmgr** [comment] 2020-03-17 23:21
I think this has been solved in version 3.10.0. Could you try with this version if the problem is still present?

**Comment by Jmgr** [comment] 2020-03-18 12:52
Should be fixed in version 3.10.0, so I'm closing this issue. Don't hesitate to create a new issue if the problem is still present in this version.

**Closed by Jmgr** 2020-03-18 12:52 UTC
Labels: question, ui
