### ISSUE TITLE
Manjaro Linux, Find image -> Capture screen part, not working

### ISSUE THREAD

**Issue by DjoleDzele** [Jmgr/actiona#197] opened 2023-08-18 16:48 UTC
I tried opening actiona in terminal to see if some error will popup but nothing, when i click on "capture screen part" i am unable to select anything on screen, sometimes it randomly gets to work 1 try out of 15, Capture whole screen and capture window works normally, what could be causing this issue?

**Comment by Jmgr** [comment] 2023-08-18 22:39
Are you using Wayland as a display manager? Actiona only works on X11.

**Comment by DjoleDzele** [comment] 2023-08-19 13:37
I'm indeed on X11, not using Walyand

**Comment by Jmgr** [comment] 2023-08-22 08:52
Hm okay, looks like this could be a bug. Thanks. I'll have a look when I get the time.

**Comment by Jmgr** [comment] 2023-08-27 20:38
I was able to reproduce the issue on Manjaro also. The "part of screen" capture is a bit hacky to be honest, so I'm not that surprised that it got broken for some reason. I don't see any immediate workaround apart from doing a screenshot with another app and editing the screenshot to keep the part you want. You can then select that image as the image to search for on the screen.

**Comment by DjoleDzele** [comment] 2023-08-27 20:47
I see... The thing is, it does sometimes work if i click and hold both mouse clicks or randomly clicking and dragging with both of mouse buttons pressed or such random combinations, and it successfully captures the part of screen i want, so could it maybe be something about registering mouse inputs incorrectly?

**Comment by Jmgr** [comment] 2024-05-06 21:39
The bug has been fixed, and the fix will be included in the next version.

**Closed by Jmgr** 2024-05-06 21:39 UTC
Labels: bug, OS: Linux distribution
